services:
  - type: web
    name: spotify-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/search?q=test
    envVars:
      - key: PORT
        value: 10000
